datainflorescences_8w <- read.table("inflorescences_8w.bias")
datainflorescences_8w_dupbias_a <- read.table("inflorescences_8w_dupbias_a")
datainflorescences_8w_dupbias_b <- read.table("inflorescences_8w_dupbias_b")
pdf("inflorescences_8w.hist.pdf",width=4,height=5)
hist(datainflorescences_8w$V3,breaks=32,col="#CCCCCC", xlim=c(-6,6), ylim=c(0,4000),border="black",xaxt='n',main="Inflorescences",xlab="")
axis(side=1, at=seq(-6,6,2))
hist(datainflorescences_8w_dupbias_a$V3, add=T, col="#66CCCC",breaks=16)
hist(datainflorescences_8w_dupbias_b$V3, add=T, col="#CC9966",breaks=16)
dev.off()

dataleaf_blade_8w <- read.table("leaf_blade_8w.bias")
dataleaf_blade_8w_dupbias_a <- read.table("leaf_blade_8w_dupbias_a")
dataleaf_blade_8w_dupbias_b <- read.table("leaf_blade_8w_dupbias_b")
pdf("leaf_blade_8w.hist.pdf",width=4,height=5)
hist(dataleaf_blade_8w$V3,breaks=32,col="#CCCCCC", xlim=c(-6,6), ylim=c(0,4000),border="black",xaxt='n',main="Leaf_blade",xlab="")
axis(side=1, at=seq(-6,6,2))
hist(dataleaf_blade_8w_dupbias_a$V3, add=T, col="#66CCCC",breaks=16)
hist(dataleaf_blade_8w_dupbias_b$V3, add=T, col="#CC9966",breaks=16)
dev.off()


dataleaf_sheath_8w <- read.table("leaf_sheath_8w.bias")
dataleaf_sheath_8w_dupbias_a <- read.table("leaf_sheath_8w_dupbias_a")
dataleaf_sheath_8w_dupbias_b <- read.table("leaf_sheath_8w_dupbias_b")
pdf("leaf_sheath_8w.hist.pdf",width=4,height=5)
hist(dataleaf_sheath_8w$V3,breaks=32,col="#CCCCCC", xlim=c(-6,6), ylim=c(0,4000),border="black",xaxt='n',main="Leaf_sheath",xlab="")
axis(side=1, at=seq(-6,6,2))
hist(dataleaf_sheath_8w_dupbias_a$V3, add=T, col="#66CCCC",breaks=16)
hist(dataleaf_sheath_8w_dupbias_b$V3, add=T, col="#CC9966",breaks=16)
dev.off()

dataroot_8w <- read.table("root_8w.bias")
dataroot_8w_dupbias_a <- read.table("root_8w_dupbias_a")
dataroot_8w_dupbias_b <- read.table("root_8w_dupbias_b")
pdf("root_8w.hist.pdf",width=4,height=5)
hist(dataroot_8w$V3,breaks=32,col="#CCCCCC", xlim=c(-6,6), ylim=c(0,4000),border="black",xaxt='n',main="Roots",xlab="")
axis(side=1, at=seq(-6,6,2))
hist(dataroot_8w_dupbias_a$V3, add=T, col="#66CCCC",breaks=16)
hist(dataroot_8w_dupbias_b$V3, add=T, col="#CC9966",breaks=16)
dev.off()

dataseed_mature <- read.table("seed_mature.bias")
dataseed_mature_dupbias_a <- read.table("seed_mature_dupbias_a")
dataseed_mature_dupbias_b <- read.table("seed_mature_dupbias_b")
pdf("seed_mature.hist.pdf",width=4,height=5)
hist(dataseed_mature$V3,breaks=32,col="#CCCCCC", xlim=c(-6,6), ylim=c(0,4000),border="black",xaxt='n',main="Seed_mature",xlab="")
axis(side=1, at=seq(-6,6,2))
hist(dataseed_mature_dupbias_a$V3, add=T, col="#66CCCC",breaks=16)
hist(dataseed_mature_dupbias_b$V3, add=T, col="#CC9966",breaks=16)
dev.off()

dataseedling_1w <- read.table("seedling_1w.bias")
dataseedling_1w_dupbias_a <- read.table("seedling_1w_dupbias_a")
dataseedling_1w_dupbias_b <- read.table("seedling_1w_dupbias_b")
pdf("seedling_1w.hist.pdf",width=4,height=5)
hist(dataseedling_1w$V3,breaks=32,col="#CCCCCC", xlim=c(-6,6), ylim=c(0,4000),border="black",xaxt='n',main="Seedlings",xlab="")
axis(side=1, at=seq(-6,6,2))
hist(dataseedling_1w_dupbias_a$V3, add=T, col="#66CCCC",breaks=16)
hist(dataseedling_1w_dupbias_b$V3, add=T, col="#CC9966",breaks=16)
dev.off()

datashoot_3w <- read.table("shoot_3w.bias")
datashoot_3w_dupbias_a <- read.table("shoot_3w_dupbias_a")
datashoot_3w_dupbias_b <- read.table("shoot_3w_dupbias_b")
pdf("shoot_3w.hist.pdf",width=4,height=5)
hist(datashoot_3w$V3,breaks=32,col="#CCCCCC", xlim=c(-6,6), ylim=c(0,4000),border="black",xaxt='n',main="Shoots",xlab="")
axis(side=1, at=seq(-6,6,2))
hist(datashoot_3w_dupbias_a$V3, add=T, col="#66CCCC",breaks=16)
hist(datashoot_3w_dupbias_b$V3, add=T, col="#CC9966",breaks=16)
dev.off()

datastem_8w <- read.table("stem_8w.bias")
datastem_8w_dupbias_a <- read.table("stem_8w_dupbias_a")
datastem_8w_dupbias_b <- read.table("stem_8w_dupbias_b")
pdf("stem_8w.hist.pdf",width=4,height=5)
hist(datastem_8w$V3,breaks=32,col="#CCCCCC", xlim=c(-6,6), ylim=c(0,4000),border="black",xaxt='n',main="Stems",xlab="")
axis(side=1, at=seq(-6,6,2))
hist(datastem_8w_dupbias_a$V3, add=T, col="#66CCCC",breaks=16)
hist(datastem_8w_dupbias_b$V3, add=T, col="#CC9966",breaks=16)
dev.off()

